### ISSUE TITLE
Communication with the service provider failed: https://api.linkedin.com/uas/oauth/requestToken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NityaNandPandey/Linkedin-SignIn#130]
```
What steps will reproduce the problem?
1. Try Launching the Activity.
2. LinkedIn will fail to return request token.
3. WebView will be blank.


I am trying to retrieve user profile from LinkedIn. But while retrieving 
request token from LinkedIn, I'm getting following error:

com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceException: 
oauth.signpost.exception.OAuthCommunicationException: Communication with the 
service provider failed: https://api.linkedin.com/uas/oauth/requestToken at 
com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceImpl.getOAuthReques
tToken(LinkedInOAuthServiceImpl.java:180)  at 
com.alumsphere.login.GetUserProfileFromLinkedIn.onCreate(GetUserProfileFromLinke
dIn.java:92)  at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)  at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)  at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)  at 
android.app.ActivityThread.access$2300(ActivityThread.java:126)  at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)  at 
android.os.Handler.dispatchMessage(Handler.java:99)  at 
android.os.Looper.loop(Looper.java:123)  at 
android.app.ActivityThread.main(ActivityThread.java:4633)  at 
java.lang.reflect.Method.invokeNative(Native Method)  at 
java.lang.reflect.Method.invoke(Method.java:521)  at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)  at 
dalvik.system.NativeStart.main(Native Method)


 Caused by: oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: https://api.linkedin.com/uas/oauth/requestToken at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:214)  at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:69)  at com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceImpl.getOAuthRequestToken(LinkedInOAuthServiceImpl.java:172)... 14 more


Caused by: java.io.FileNotFoundException: 
https://api.linkedin.com/uas/oauth/requestToken  at 
org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.get
InputStream(HttpURLConnectionImpl.java:1162)  at 
org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl.g
etInputStream(HttpsURLConnectionImpl.java:253)  at 
oauth.signpost.basic.HttpURLConnectionResponseAdapter.getContent(HttpURLConnecti
onResponseAdapter.java:18)  at 
oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvi
der.java:228)  at 
oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:18
9)... 16 more

The code I'm using was working before. It has stopped few days back 
unexpectedly. Attached is my code. Please reply as soon as possible.

```

Original issue reported on code.google.com by `mishu311...@gmail.com` on 6 Dec 2012 at 10:53

**Comment by GoogleCodeExporter** [comment]
```
I have also tried placing request twice i.e. in catch block of first request. 
Also tried synchronizing time but that doesn't work either.
```

Original comment by `mishu311...@gmail.com` on 6 Dec 2012 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Hi Team,

This is a gentle reminder. My project is stuck in between. Please give some 
help regarding this issue.
```

Original comment by `mishu311...@gmail.com` on 11 Dec 2012 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The error has now changed to 

Caused by: 
com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceException: 
oauth.signpost.exception.OAuthCommunicationException: Communication with the 
service provider failed: Host is unresolved: api.linkedin.com:443

I haven't changed my code. Also I've added internet permission in manifest file.

Please tell if I am doing anything wrong.
```

Original comment by `mishu311...@gmail.com` on 13 Dec 2012 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
getting same problem. it doesn't seem to work . still i couldn't fix
```

Original comment by `doga.ozkaraca@gmail.com` on 7 Jul 2015 at 6:26
